/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tmrlpfjjczwvrahisslp"
export const publicAnonKey = "REPLACE_WITH_NEW_PROJECT_ANON_KEY" // from Settings → API on the tmrlpfjjczwvrahisslp project