/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tmrlpfjjczwvrahisslp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtcmxwZmpqY3p3dnJhaGlzc2xwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAyNjQyMjAsImV4cCI6MjEwNTg0MDIyMH0.I0R0IodtJAXbRbE81R0PXAD2XZYgmcLHEZJYXHXOTWg" // from Settings → API on the tmrlpfjjczwvrahisslp project